name: Checks

on:
  pull_request:
    branches:
      - master
    paths:
      # Not restricting paths for now as there might be updates to the SDKs which change the
      # outcome of these actions between different commits, even when there was no package change.
      - '**'
#      - '**/lib/**'
#      - '**/pubspec.yaml'
#      - '**/test/**'

jobs:
  analyze:
    timeout-minutes: 6
    runs-on: ${{ matrix.os }}
    name: Analysis & format (${{ matrix.channel }} on ${{ matrix.os }})
    strategy:
      matrix:
        os:
          - ubuntu-latest
        channel:
          - 'stable'
          - 'beta'
          - 'dev'
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      # Need to manually maintain the correct Flutter versions here as the subosito Flutter action
      # does not seem to use the latest versions in the channels.
      # https://github.com/subosito/flutter-action/issues/50
      # Always check https://flutter.dev/docs/development/tools/sdk/releases to update these
      # version numbers accordingly.
      - uses: subosito/flutter-action@v1.3.2
        if: matrix.channel == 'stable'
        with:
          flutter-version: 1.17.4
      - uses: subosito/flutter-action@v1.3.2
        if: matrix.channel == 'beta'
        with:
          flutter-version: 1.19.0-4.2.pre
      - uses: subosito/flutter-action@v1.3.2
        if: matrix.channel == 'dev'
        with:
          flutter-version: 1.20.0-2.0.pre

      - name: Setup projects
        run: |
          flutter pub get

          cd example
          flutter create .
          rm -rf test
          flutter pub get

          cd ../demo
          flutter pub get

          cd ..

      - name: Check format (flutter format)
        if: matrix.channel == 'stable'
        run: flutter format . --set-exit-if-changed --fix

      - name: Check format (dart format)
        if: matrix.channel != 'stable'
        run: dart format .

      - run: flutter analyze

  test:
    timeout-minutes: 6
    runs-on: ${{ matrix.os }}
    name: Test (${{ matrix.channel }} on ${{ matrix.os }})
    strategy:
      matrix:
        os:
          - ubuntu-latest
        channel:
          - 'stable'
          - 'beta'
          - 'dev'
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      # Need to manually maintain the correct Flutter versions here as the subosito Flutter action
      # does not seem to use the latest versions in the channels.
      # https://github.com/subosito/flutter-action/issues/50
      # Always check https://flutter.dev/docs/development/tools/sdk/releases to update these
      # version numbers accordingly.
      - uses: subosito/flutter-action@v1.3.2
        if: matrix.channel == 'stable'
        with:
          flutter-version: 1.17.4
      - uses: subosito/flutter-action@v1.3.2
        if: matrix.channel == 'beta'
        with:
          flutter-version: 1.19.0-4.2.pre
      - uses: subosito/flutter-action@v1.3.2
        if: matrix.channel == 'dev'
        with:
          flutter-version: 1.20.0-2.0.pre

      - name: Setup project
        run: flutter pub get

      - name: Run unit tests
        run: flutter test

  pana:
    timeout-minutes: 9
    runs-on: ubuntu-latest
    name: Pub PANA

    steps:
      - uses: actions/checkout@v2

      - name: Clean up directory # Matches the publish workflow.
        run: rm -rf .github demo gen CODEOWNERS CONTRIBUTING.md function_prioritization.csv

      - uses: axel-op/dart-package-analyzer@v2
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
